### ISSUE TITLE
Strategy for OSD's goals, user base, platform and growth

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/organization#73]
Due to discussion in #69 about "discussion platforms" I figured I should outline the unofficial strategy I've envisioned for OSD to grow and thrive:

### 1. Use GitHub for temporary infrastructure

- Free as in cost
- Simple mailing list like functionality
- Code (used for content) revision / hosting
- A bridge that makes it easy for developers to engage
- Experiment & prototype data structures (jobs, events, resources, etc...)
- Low barrier to entry static website creation
- Make data easily readable & portable (markdown files)

The *only* barrier to using it is *a Github account* and basic understanding to use the "issues" tab (for discussion) and checking your email, and for us (as organizers) to keep repos, topics, and threads organized.

### 2. Combine, iterate and improve components

Tools and platforms which are more user friendly / cater to designers, project managers, etc... and facilitate frictionless collaboration and productivity between designers and devs are very needed. However, there's few offerings that meet everyones needs and even less which are open source.
Thus, i've always envisioned realizing this step. by using small hacks and clever improvements of existing open source apps and components. Some of my recent efforts towards this:

**1. Chat Platform**

- [chat.opensourcedesign.net](https://chat.opensourcedesign.net) - ask for an account #70

Next is to improve the chat / IRC interface to meet our needs so it's closer to Slack, but also oriented towards productivity and collaboration- than just "slacking off" and general chat. I'm going to be resuming work on [Slick](/opensourcedesign/slick) to achieve this goal, I could use help :smile:

**2. User Friendly Page Editing**

- [Open Source Design Editor](https://edit.opensourcedesign.net) - Prose instance (just setup)

Getting people to fork repos and send pull requests is technical and difficult for designers as well as people familiar with blogging or CMS's. Hopefully, the [Prose](http://prose.io) editor will make this easier for everyone to contribute to the site. However, I do think the Prose interface can still be improved upon for our use cases and am filing bugs with their project.

**3. Simple Web Forms**
 
- [Add job form](http://opensourcedesign.net/jobs/job-form/) 

When we combine simple forms like this with the Prose editor, we get an almost CMS like experience built on top of Github (with a mild server dependency which I am happy to run on my server).

- [Prose Editor - Contribute page](https://edit.opensourcedesign.net/#opensourcedesign/opensourcedesign.github.io/edit/master/contribute.md) (requires Github authenticating)

My goal / hope is that we **make more simple web forms** so random things like:

> "Using Tool X for task Y is really helpful" 

Will end up getting added to a beautifully designed page on our website (with good SEO), that's not buried in a forum thread somewhere (like the rest of the non-designer friendly FOSS eco-system). Thus, I advocate for creating:

- [ ] Web form for Resources - opensourcedesign/opensourcedesign.github.io#82
- [ ] Web form for Events - opensourcedesign/opensourcedesign.github.io#81
- [ ] Web form for People - opensourcedesign/opensourcedesign.github.io#79

With those three proposed forms (and our current job form), as well as these refining these other things, I think we will be in pretty good shape for running an open open source community that allows people of differing skills and abilities to participate. 

### 3. Create new platforms & tools

This is the least thought out part of my strategy as we are still pretty much in step 1., but I think projects like [UXBox](http://uxbox.com) are already doing this, hats off to that whole team 😀 

### Alternatively

Maybe, i'm just thinking too much like a "web dev" who sees the possibilities of how easy some of this is to achieve if other designer / devs put in a little bit of effort. Overall, if what "open source design" means to many others is just sharing designs and having general conversations- a plan like what i'm proposing is overkill and more work and we should just setup a Discourse site.

Regardless, I'm curious to hear feedback on this proposal.

**Comment by jdittrich** [comment]
Thanks for clarifying your ideas!

> Overall, if what "open source design" means to many others is just sharing designs and having general conversations- a plan like what i'm proposing is overkill and more work and we should just setup a Discourse site.

Am I right assuming that you think that "sharing designs" and "having general conversations" [about open source design work] are not desirable from your  point of view? If that assumption is right – What is the reasoning behind that?

**Comment by pdurbin** [comment]
@bnvk nice write up. Two questions:

- Is "What We Want to Achieve" at http://opensourcedesign.net/about/ still more or less accurate?
- Should "How We Plan To Achieve This" on the same page be updated to include some of the strategies you've suggested?

**Comment by bnvk** [comment]
@pdurbin yes the OSD "What We Want to Achieve" is still totally accurate. This 
is just my "technical" proposal for achieving some of that- which I realized 
might have only been in *my* head. Good call on adding to the "How...", but
I wanna make sure there's enough consensus buy-in first :)

**Comment by studiospring** [comment]
The OSD goals seem quite open to interpretation, but the way I see it, the goal is to **improve the user experience of open source software**. How?

1. Advocate its value among all stakeholders, particularly designers and developers. 
  a. Case studies.
  b. Publicity (events, outreach, etc)

2. Facilitate open source design for all stakeholders, particularly designers and developers.
  a. Change the [value-exchange system](https://www.quora.com/Why-does-open-source-software-usually-have-poor-UI-and-UX-design-What-can-be-done-to-improve-this) of open source software.
  b. Provide the necessary knowledge/tools/platforms for OSD.
    ....i. A means of collaboration.
    ....ii. Resources, like how-to guides/wiki, for all stakeholders (not just designers).
    ....iii. A skills-to-project matching service (as we already have).

One pattern that I see emerging is the need to break down silos. The poster child is of course GitHub. This is a developer silo, where developers are (quite successfully) doing it all on their own. Design is as much (if not more!) about facilitation, as it is about pumping out prototypes, so if OSD becomes a designer silo, then I consider it a failed endeavour. That is why I consider collaboration tools (including, but not only for designers) to be so important.

But before any of this can be done, there needs to be more research in to this whole business because no one (including myself) seems to know the best approach. The common ground we stand on is the need for better UX in open source software. Beyond that is unknown territory.

**Comment by jdittrich** [comment]
>  more research in to this whole business because no one (including myself) seems
>  to know the best approach.

There is https://github.com/victoria-bondarchuk/List-of-Academic-Research-on-Usability-in-FOSS by @victoria-bondarchuk 
@victoria-bondarchuk: Do you know of a good review of problems based on the research (or would you like to collaborate on writing one?)

**Comment by bnvk** [comment]
Silos are not ideal. I'm all for blurring lines and building bridges, but I 
wouldn't call GitHub a failure of being a silo as we (a community of designers) 
have grown and made our home amidst this silo of developers- network effects 
can be useful :)

> more research in to this whole business because no one (including myself)
> seems to know the best approach.

I am curious @studiospring do you mean the same kind of research @jdittrich is 
referencing with @victoria-bondarchuk collection?

My thinking informing my strategy above comes intuitively from my 15 years
working at studios, startups, agencies, and freelancing directly for clients
as a designer and developer mixed with some idealism.

However, the "physics" of FOSS is different due to the lack of money and 
industry driving things.

> common ground we stand on is the need for better UX in open source software

Yep!!! The job board was one piece of one strategy towards this. As I see it, 
applying for grants (to fund design + code work) is a next step in this
direction.

> Beyond that is unknown territory.

Exciting- let's chart some more courses :)

**Comment by studiospring** [comment]
@bnvk, I do not think GitHub is a failure, it is a finely honed tool for developers. However, because it is so well tailored to developers' abilities, it excludes other stakeholders and turns in to a silo. I suspect most OSD members have some dev experience and are not pure designers. A platform for design cannot afford to do this (IMHO) because design is all about collaboration _between different stakeholders_.

@victoria-bondarchuk's collection is certainly a good start. However, I am thinking more along the lines of standard user research that you would use in a design project. I want to understand the needs, pain points and motivations of the various stakeholders, so that we can develop personas, user journeys and the like. I do not even know what kind of people our own community is made up of. Am I talking to UX designers, developers, is everyone running Linux, am I the only one with these frustrations...?

I would also like to eventually gauge how successful our efforts are, so that we know which strategies work and which do not. This is part of the standard feedback and iteration loop of lean/agile design. Ideally a "usability index" of open source software and other feedback on our efforts would help us understand how we are doing. I am aware of a couple of other [surveys](https://github.com/github/open-source-survey) in the past, but they have different agendas and do not answer our questions.

I would like to set up an annual OSD online survey to help us get a better idea of our stakeholders (including ourselves) and how to go forward and how we have progressed. I will cover some of these points in my OSD blog post that I am working on. I intend to create a new issue (or please feel free to do so for me) specifically about an online survey if people are willing to pitch in.

**Comment by simonv3** [comment]
> I would like to set up an annual OSD online survey to help us get a better idea of our stakeholders (including ourselves) and how to go forward and how we have progressed. I will cover some of these points in my OSD blog post that I am working on. I intend to create a new issue (or please feel free to do so for me) specifically about an online survey if people are willing to pitch in.

Yes!

**Comment by jdittrich** [comment]
> I want to understand the needs, pain points and motivations of the various stakeholders, 
> so that we can develop personas, user journeys and the like.

There is quite a lot of practical results and advice in the research collection; I really want to do our own research, too, but it seems to be a useful start.

**Comment by jdittrich** [comment]
> I would also like to eventually gauge how successful our efforts are, so that we know which strategies work and which do not.

Would love to have this, too, but it seems hard to measure. 

>  I do not even know what kind of people our own community is made up of. Am I talking to UX designers, developers, is everyone running Linux, am I the only one with these frustrations

This may be a good survey topic, indeed. 

> I would like to set up an annual OSD online survey to help us get a better idea of our stakeholders 
If you say stakeholders, do you mean internal stakeholders, like Graphic Designers, User Researchers etc. or external ones which are not part of the OSD-Community (yet) and may be programmers, project managers, designers…

I’m asking since that may need different questions and design for asking them. 

> I would like to set up an annual OSD online survey

I like that idea and I could help in creating this – at least in terms of methodology and analysis. @HeikoTietze may also be interested (?)

**Comment by studiospring** [comment]
@jdittrich, please see #77 for answers to your questions.

**Comment by grahamperrin** [comment]
> … just setup a Discourse site.

+[100 percent](https://github.com/opensourcedesign/organization/issues/69#issuecomment-286582566) from me …

**Comment by simonv3** [comment]
... @grahamperrin so can we sign up to discourse?

**Comment by grahamperrin** [comment]
In #79 I'm reasonably close to 'opening up' the recently begun Discourse instance for an _open source design_ **forum** for

- _Open Source Design (OSD) and related communities_ 

– that phrase is not set in stone; kick the ball around, if you like. 

#68 began for the **logo** and expanded to include discussion of **brand and identity**. 

https://github.com/opensourcedesign/opensourcedesign.github.io/pull/89 by @studiospring was for recently published [Open source design needs better collaboration tools](http://opensourcedesign.net/open-source/communities/collaboration/tools/design/2017/03/27/osd-needs-better-collaboration-tools.html), which strikes me as a good topic for early discussion in the forum. (Sean, how does that sound to you? Ping me at ircs://chat.freenode.net/#opensourcedesign or e-mail, if you prefer.)

Technically the forum will work without an OSD logo. However … 

## Strategically

Should we defer opening of the forum until the new logo becomes available?

Please share your thoughts. Thanks.

**Comment by studiospring** [comment]
> Open source design needs better collaboration tools, which strikes me as a good topic for early discussion in the forum

@grahamperrin I'm fine with that though I'm sure there will be plenty of other topics to discuss ;-)

Unless a soon-ish date can be set for the new logo, I would rather not postpone Discourse, when we can easily just update the logo later. Maybe choosing the logo is a more appropriate first topic for Discourse :D

**Comment by grahamperrin** [comment]
Recommended reading, for anyone with an interest in preparations for the forum: 

- [Building a Discourse Community](https://blog.discourse.org/2014/08/building-a-discourse-community/) (2014-08-01)

– in particular, _What is your community’s purpose?_ 

> … pinned welcome topic, or banner topic, … will appear for every visitor, forever, and people are busy. So:
> 
> -    Keep it brief
> -    Put your very best copy here 
> 
> … elevator pitch or mission statement describing what your community is and does. For those who want to learn more, it can also link to a deeper explanation of your community, the benefits of joining, and so forth. …

Re: https://github.com/opensourcedesign/organization/issues/12 it's clear (from the **mission** part of the by-laws) that OSD is: 

> a community of designers and developers pushing more open design processes and improving the design of open source apps.

## Towards an elevator pitch

For what it's worth, I prefer the home page definition of OSD: 

> a community of designers and developers pushing more open design processes and improving the user experience and interface design of open source software.

To that single sentence I might add the seven numbered **goals** from http://opensourcedesign.net/about/ –

> open up the design process – make designers contributors – communication between designers and developers – connect the existing open source design community – funding for open source design – showcase existing open source design material – work on improving the design of open source projects

– and last but not least, **the plan**: 

> creation of an awesome and inclusive community that attracts talented and passionate people. 

## Towards a banner/welcome topic in the forum

> **Open Source Design** (OSD) is [a community](http://opensourcedesign.net) of designers and developers pushing more open design processes and improving the user experience and interface design of open source software. In this forum, and in other OSD channels, we welcome talented and passionate people – **an awesome and inclusive community** to realise [goals](http://opensourcedesign.net/about/) such as these: 
> 
> - greater openness in design processes
> - more contributions to open source from designers
> - greater communication between designers and developers
> - better connections within and across open source design communities
> - funding for open source design initiatives
> - increased showcasing of open source design materials
> - improvements to the design of open source projects.

This, from a more established forum, should offer an indication of how a banner of that length _might_ appear. Assume that not all seven bullet points will be immediately visible – 

![a green banner at the discourse forum for manjaro](https://cloud.githubusercontent.com/assets/192271/24836472/9c1b8fc6-1d14-11e7-980d-0e4dde427fcf.png)

– newcomers can either scroll to reveal the last of the points, or click the word _goals_. 

(Beyond a banner: answers to frequently asked questions include a link to OSD by-laws, and so on.) 

### Your thoughts please

Will a banner such as that fit with the **goals, user base, platform and growth** focus of this issue 73? 

I ask here (not in 79) because a strategic approach should not focus on building the forum in isolation …

**Comment by ei8fdb** [comment]
> I would also like to eventually gauge how successful our efforts are, so that we know which strategies work and which do not.
@studiospring can you give some specific questions you might want to answer as part of "how successful our efforts are....which strategies work and which do not"

>  However, I am thinking more along the lines of standard user research that you would use in a design project. I want to understand the needs, pain points and motivations of the various stakeholders, so that we can develop personas, user journeys and the like.

Finally someone mentions users and understanding them!

> I do not even know what kind of people our own community is made up of. Am I talking to UX designers, developers, is everyone running Linux, am I the only one with these frustrations

I think you'll find the (current) OSD community is more diverse than what you've mentioned here. But I completely agree with you - we need to find out about our community members.

> I would like to set up an annual OSD online survey
@studiospring @jdittrich Before this it would be very helpful to carry out some interviews with members. This will help inform the design of the survey.

>> I like that idea and I could help in creating this – at least in terms of methodology and analysis. 
I'd also like to be part of this.

**Comment by studiospring** [comment]
@ei8fdb great to find another interested member! As an open source project, I am trying to make it as collaborative as possible. Anyone can be involved in (almost) any part of it. At the moment, I am thinking of waiting until the Discourse forum is officially open and members have settled in before creating the survey repo.

**Comment by ei8fdb** [comment]
> I am thinking of waiting until the Discourse forum is officially open and members have settled in before creating the survey repo.

It would be interesting to get a better understanding of our current community, since our beginning. It might make for an interesting comparison once the Discourse site is in use.

I have met many people and still don't know 70-80% of people's backgrounds.

**Comment by studiospring** [comment]
> It would be interesting to get a better understanding of our current community, since our beginning. It might make for an interesting comparison once the Discourse site is in use.

That could be done in the survey by comparing current GitHub members with other respondents.

> I have met many people and still don't know 70-80% of people's backgrounds.

By using [user cards](https://meta.discourse.org/t/what-are-user-cards/44093) that should be easier in Discourse than in GitHub. Personally, I would also like pre-defined icons next to a person's avatar/name, but that's another issue...

**Comment by jdittrich** [comment]
It was suggested to do wording suggestions for the banner on discourse here. I am not sure if that is the right place and would rather see this at #79. 

Wording: 

* I would ditch the "goals such as these" list. It makes it long and weakens the goals already stated: "pushing more open design processes and improving the user experience and interface design of open source software."
* "In this forum, and in other OSD channels, we welcome talented and passionate people – an awesome and inclusive community to realize goals such as these" -> "Here and in the other OSD channels, we strive to be an awesome and inclusive community". So it deletes the vague "such as these" and also the "talented and passionate", since who decides about "talent" (see "inclusive") and neither do I see "passion" as a value in itself.

So, with some additional shortening it would become: 

> **Open Source Design** (OSD) is a community of designers and developers pushing ~~more~~ open design processes and improving the user experience ~~and interface design~~ of open source software. Here, and in the other OSD channels, we strive to be an awesome and inclusive community

Which you can read in a glance.

**Comment by ei8fdb** [comment]
@jdittrich I also was confused by the suggestion to post here.

> I would ditch the "goals such as these" list. It makes it long and weakens the goals already stated

I agree. The start page will show whats available to the user without the need to explain it to the user.

> "In this forum, and in other OSD channels, we welcome talented and passionate people – an awesome and inclusive community to realize goals such as these"

Ditto.

I keep harping on about user research and so I'd like to ask "researchers" to be included...so to read:

> Open Source Design (OSD) is a community of researchers, designers and developers pushing more open design processes and improving the user experience of open source software. Here, and in the other OSD channels, we strive to be an awesome and inclusive community.

**Comment by grahamperrin** [comment]
In this issue, because the forum is not an isolated channel. 

> ## Strategy for OSD's goals, user base, platform and growth

A strategic approach should offer reasonably consistent messages, consistent definitions of the community, across **all** channels.

**Comment by jdittrich** [comment]
@ei8fdb: 
* I would love more *researchers* as well. 
* OR we could ditch the specific roles (do they matter?) and go for community of people/enthusiasts/…
* OR say: 'designer and developer' they are just a graspable stand-in for 'cross disciplinary work'

@grahamperrin: Ok, I saw this as a clarification of @bnvk’s ideas not as our general strategy discussion. @bnvk – or should it be?

**Comment by ei8fdb** [comment]
@jdittrich In reality of the work I don't care about job roles, I care that the research is being done, properly. If the person doing the research, design, and development is the same person, great. Difficult, but great.

I expect the subject of research to be mentioned. That is the important point.

The lack of research into whats actually needed gets us where we are with crappy software.

What about:

> "Open Source Design (OSD) is a community pushing  research, design and development of more open design processes and improving the user experience of open source software."

If not, and we want to keep with job roles, then @grahamperrin please add the word "researcher".

**Comment by bnvk** [comment]
Closing this issue as it has become far too meta-meta and branching into far too many splinters to be useful for achieving anything or even for me to follow along.
